"""
Anthropic token-based authentication using session tokens from `claude setup-token`.

This provides an alternative to API keys by using session tokens generated by
Anthropic's official Claude CLI tool.
"""

import json
import os
from pathlib import Path
from typing import Optional, Dict


DEFAULT_AUTH_FILE = os.path.expanduser("~/.litellm/anthropic-tokens.json")


def validate_anthropic_setup_token(token: str) -> Optional[str]:
    """
    Validate an Anthropic setup-token format.

    Args:
        token: The token to validate

    Returns:
        None if valid, error message if invalid
    """
    token = token.strip()

    if not token:
        return "Token cannot be empty"

    # Anthropic setup tokens typically start with "sk-ant-" followed by base64-like chars
    # But setup-token format may differ from API keys
    if len(token) < 20:
        return "Token too short (minimum 20 characters)"

    # Basic validation - should not contain whitespace
    if any(c.isspace() for c in token):
        return "Token contains invalid whitespace"

    return None


def load_token_storage(auth_file: str = DEFAULT_AUTH_FILE) -> Dict:
    """Load stored tokens from file."""
    auth_path = Path(auth_file)

    if not auth_path.exists():
        return {"profiles": {}}

    try:
        with open(auth_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        raise Exception(f"Failed to load auth file {auth_file}: {e}")


def save_token_storage(data: Dict, auth_file: str = DEFAULT_AUTH_FILE):
    """Save tokens to file."""
    auth_path = Path(auth_file)
    auth_path.parent.mkdir(parents=True, exist_ok=True)

    with open(auth_path, 'w') as f:
        json.dump(data, f, indent=2)

    # Set file permissions to 600 (owner read/write only)
    auth_path.chmod(0o600)


def store_anthropic_token(
    token: str,
    profile_id: str = "anthropic:manual",
    expires_days: Optional[int] = None,
    auth_file: str = DEFAULT_AUTH_FILE
):
    """
    Store an Anthropic setup-token.

    Args:
        token: The setup-token from `claude setup-token`
        profile_id: Profile identifier (default: "anthropic:manual")
        expires_days: Optional expiration in days
        auth_file: Path to auth storage file
    """
    # Validate token
    error = validate_anthropic_setup_token(token)
    if error:
        raise ValueError(f"Invalid token: {error}")

    # Load existing storage
    storage = load_token_storage(auth_file)

    # Calculate expiration if specified
    expires_ms = None
    if expires_days is not None:
        import time
        expires_ms = int((time.time() + (expires_days * 86400)) * 1000)

    # Store token
    if "profiles" not in storage:
        storage["profiles"] = {}

    storage["profiles"][profile_id] = {
        "type": "token",
        "provider": "anthropic",
        "token": token,
        **({"expires": expires_ms} if expires_ms else {})
    }

    save_token_storage(storage, auth_file)
    print(f"✅ Token stored: {profile_id}")


def get_anthropic_token(
    profile_id: str = "anthropic:manual",
    auth_file: str = DEFAULT_AUTH_FILE
) -> Optional[str]:
    """
    Retrieve stored Anthropic token.

    Args:
        profile_id: Profile identifier
        auth_file: Path to auth storage file

    Returns:
        Token string or None if not found/expired
    """
    storage = load_token_storage(auth_file)

    profile = storage.get("profiles", {}).get(profile_id)
    if not profile:
        return None

    # Check expiration
    if "expires" in profile:
        import time
        if time.time() * 1000 > profile["expires"]:
            print(f"⚠️  Token expired for profile: {profile_id}")
            return None

    return profile.get("token")


def setup_token_interactive():
    """
    Interactive setup for Anthropic token.
    Guides user through the claude setup-token flow.
    """
    print("\n" + "="*70)
    print("ANTHROPIC TOKEN SETUP")
    print("="*70)
    print("\nThis will configure LiteLLM to use tokens from `claude setup-token`")
    print("instead of API keys.")
    print("\n" + "="*70)

    # Check if claude CLI is installed
    import subprocess
    try:
        result = subprocess.run(
            ["claude", "--version"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            print(f"\n✅ Claude CLI found: {result.stdout.strip()}")
        else:
            print("\n⚠️  Claude CLI not found or not working")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        print("\n❌ Claude CLI not installed")
        print("\nTo install:")
        print("  npm install -g @anthropic-ai/claude-cli")
        print("  # or")
        print("  pip install anthropic-claude-cli")
        print("\nThen run: claude setup-token")
        return False

    # Prompt for confirmation
    print("\n" + "="*70)
    response = input("Have you run `claude setup-token` and copied the token? (y/N): ")
    if response.lower() != 'y':
        print("\n❌ Setup cancelled")
        print("\nTo continue:")
        print("  1. Run: claude setup-token")
        print("  2. Copy the token it generates")
        print("  3. Run this setup again")
        return False

    # Get token input
    print("\n" + "="*70)
    token = input("Paste your Anthropic setup-token: ").strip()

    # Validate
    error = validate_anthropic_setup_token(token)
    if error:
        print(f"\n❌ Invalid token: {error}")
        return False

    # Optional expiration
    print("\n" + "="*70)
    response = input("Does this token expire? (y/N): ")
    expires_days = None
    if response.lower() == 'y':
        try:
            days_str = input("Expires in how many days? (default: 365): ").strip()
            expires_days = int(days_str) if days_str else 365
        except ValueError:
            print("⚠️  Invalid number, using 365 days")
            expires_days = 365

    # Store token
    try:
        store_anthropic_token(token, expires_days=expires_days)
        print("\n" + "="*70)
        print("✅ SUCCESS!")
        print(f"Token saved to: {DEFAULT_AUTH_FILE}")
        print("\nYou can now use Anthropic models with:")
        print("  model='anthropic/claude-3-5-sonnet-20241022'")
        print("\nLiteLLM will automatically use your token instead of API key.")
        print("="*70)
        return True
    except Exception as e:
        print(f"\n❌ Failed to store token: {e}")
        return False
